### ISSUE TITLE
Waiting for Kubero UI to be created

### ISSUE THREAD

**Issue by servicepipe** [kubero-dev/kubero#173]
The installation gets stuck here "Waiting for Kubero UI to be created" and takes a lot of time and nothing happens in the end. How to be? and how to install the panel?

**Comment by mms-gianni** [comment]
This step tries to bring up the Kubero UI container. This is checked by this command : 

```bash
kubectl get --ignore-not-found deployment kubero -n kubero
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
kubero   1/1     1            1           1m
```

But the root cause may be somewhere else: The UI is installed by the Operator with a CRD. If this step is failed, skipped or not finished, it will be stuck in this step. 

To check the Operator run :
```
kubectl get pods -n kubero-operator-system
NAME                                                  READY   STATUS    RESTARTS       AGE
kubero-operator-controller-manager-754c76499d-tbtkh   2/2     Running   0              1h
```

An successful installation should look like this: 
![image](https://github.com/kubero-dev/kubero/assets/2052196/ff457d24-eb47-43ee-924d-59369cfb8bf7)

**Comment by servicepipe** [comment]
The problem was solved with an update kubernetes https://github.com/kubernetes/kubernetes/issues/80541
