### ISSUE TITLE
multiple ports

### ISSUE THREAD

**Issue by Geczy** [kubero-dev/kubero#200]
any support for a docker container that exposes multiple ports and needs url's mapped to them separately?

**Comment by mms-gianni** [comment]
Actually no. And it's not planned since it would add too much complexity. Every port would require an Ingress with URL, Cert and Service ... 

The best workaround is to create 2 separate apps in the same pipeline and phase with the same container image. 

This adds some overhead since it requires an additional pod. But it also allows to scale separately.
